apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: srikavyapendiala/react:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://localhost:8080/api/v1/employees
